import db from '../../config/db.js';

export async function up() {
  try {
    await db.query(`
      CREATE TABLE base_bottle (
        id              integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        base_id         integer NOT NULL,
        transaction_id  integer NOT NULL,
        date_opened     timestamp(3),
        date_finished   timestamp(3),
        quantity        integer NOT NULL DEFAULT 100,
        CONSTRAINT base_bottle_base_fk
            FOREIGN KEY (base_id) REFERENCES base(base_id)
            ON UPDATE CASCADE ON DELETE RESTRICT,
        CONSTRAINT base_bottle_txn_fk
            FOREIGN KEY (transaction_id) REFERENCES transactions(id)
            ON UPDATE CASCADE ON DELETE RESTRICT
        );
    `);
  } catch (error) {
    console.log(error)
  }
}

export async function down() {
  try {
    await db.query('DROP TABLE IF EXISTS base_bottle');
  } catch (error) {
    console.log(error)
  }
}

up()