import db from '../../config/db.js';

export async function up() {
  try {
    await db.query(`
      CREATE TABLE IF NOT EXISTS base (
        base_id         integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        brand           text NOT NULL,
        name            text NOT NULL,
        ml              integer NOT NULL,
        img_path        text NOT NULL,
        base_type_name  text NOT NULL,
        present         boolean NOT NULL,
        CONSTRAINT base_base_type_fk
            FOREIGN KEY (base_type_name) REFERENCES base_type(name)
            ON UPDATE CASCADE ON DELETE RESTRICT,
        CONSTRAINT base_brand_name_ml_key UNIQUE (brand, name, ml)
        );
    `);
  } catch (error) {
    console.log(error)
  }
}

export async function down() {
  try {
    await db.query('DROP TABLE IF EXISTS base');
  } catch (error) {
    console.log(error)
  }
}

up()