import db from '../../config/db.js';

export async function up() {
  try {
    await db.query(`
      CREATE TABLE IF NOT EXISTS drink_recipe (
        drink_id    integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        name        text NOT NULL,        -- references drink.name
        ingredient  text NOT NULL,
        quantity    integer NOT NULL,
        unit        text NOT NULL,
        CONSTRAINT drink_recipe_drink_fk
            FOREIGN KEY (name) REFERENCES drink(name)
            ON UPDATE CASCADE ON DELETE RESTRICT,
        CONSTRAINT drink_recipe_unit_fk
            FOREIGN KEY (unit) REFERENCES unit(name)
            ON UPDATE CASCADE ON DELETE RESTRICT,
        CONSTRAINT drink_recipe_name_ingredient_key UNIQUE (name, ingredient)
        );
    `);
  } catch (error) {
    console.log(error)
  }
}

export async function down() {
  try {
    await db.query('DROP TABLE IF EXISTS drink_recipe');
  } catch (error) {
    console.log(error)
  }
}

up()