import db from '../../config/db.js';

export async function up() {
  try {
    await db.query(`
      CREATE TABLE IF NOT EXISTS transactions (
        id        integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        item      text NOT NULL,
        brand     text NOT NULL,
        category  text NOT NULL,
        date      timestamp(3) NOT NULL,
        price     double precision NOT NULL
        );
    `);
  } catch (error) {
    console.log(error)
  }
}

export async function down() {
  try {
    await db.query('DROP TABLE IF EXISTS transactions');
  } catch (error) {
    console.log(error)
  }
}

up()