import db from '../../../config/db.js';

export async function up() {
  try {
    await db.query(`
      CREATE TABLE IF NOT EXISTS drink_variant (
        variant_id        integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        drink_id          integer NOT NULL,   -- references drink_recipe.drink_id
        base_drink        text NOT NULL,      -- references drink.name
        variant_name      text NOT NULL,
        img_overlay_path  text,
        notes             text,
        CONSTRAINT drink_variant_base_drink_fk
            FOREIGN KEY (base_drink) REFERENCES drink(name)
            ON UPDATE CASCADE ON DELETE RESTRICT,
        CONSTRAINT drink_variant_recipe_fk
            FOREIGN KEY (drink_id) REFERENCES drink_recipe(drink_id)
            ON UPDATE CASCADE ON DELETE RESTRICT,
        CONSTRAINT drink_variant_base_name_key UNIQUE (base_drink, variant_name)
        );
    `);
  } catch (error) {
    console.log(error)
  }
}

export async function down() {
  try {
    await db.query('DROP TABLE IF EXISTS drink_variant');
  } catch (error) {
    console.log(error)
  }
}

up()