-- ======================
-- Core reference tables
-- ======================

-- DONE
CREATE TABLE unit (
  name         text PRIMARY KEY,
  unit_type    text NOT NULL,
  base_unit    text NOT NULL,
  multiplier   double precision NOT NULL
);

-- DONE
CREATE TABLE transactions (
  id        integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  item      text NOT NULL,
  brand     text NOT NULL,
  category  text NOT NULL,
  date      timestamp(3) NOT NULL,
  price     double precision NOT NULL
);

-- ======================
-- Liquor
-- ======================

-- DONE
CREATE TABLE liquor_type (
  name  text PRIMARY KEY
);

-- DONE
CREATE TABLE liquor (
  liquor_id    integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  brand        text NOT NULL,
  name         text NOT NULL,
  ml           integer NOT NULL,
  abv          integer NOT NULL,
  img_path     text NOT NULL,
  liquor_type_name text NOT NULL,
  present      boolean NOT NULL,
  CONSTRAINT liquor_liquor_type_fk
    FOREIGN KEY (liquor_type_name) REFERENCES liquor_type(name)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT liquor_brand_name_ml_key UNIQUE (brand, name, ml)
);

-- DONE
CREATE TABLE liquor_bottle (
  id              integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  liquor_id       integer NOT NULL,
  transaction_id  integer NOT NULL,
  date_opened     timestamp(3),
  date_finished   timestamp(3),
  quantity        integer NOT NULL DEFAULT 100,
  CONSTRAINT liquor_bottle_liquor_fk
    FOREIGN KEY (liquor_id) REFERENCES liquor(liquor_id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT liquor_bottle_txn_fk
    FOREIGN KEY (transaction_id) REFERENCES transactions(id)
    ON UPDATE CASCADE ON DELETE RESTRICT
);

-- ======================
-- Base
-- ======================

-- DONE
CREATE TABLE base_type (
  name  text PRIMARY KEY
);

-- DONE
CREATE TABLE base (
  base_id         integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  brand           text NOT NULL,
  name            text NOT NULL,
  ml              integer NOT NULL,
  img_path        text NOT NULL,
  base_type_name  text NOT NULL,
  present         boolean NOT NULL,
  CONSTRAINT base_base_type_fk
    FOREIGN KEY (base_type_name) REFERENCES base_type(name)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT base_brand_name_ml_key UNIQUE (brand, name, ml)
);

-- DONE
CREATE TABLE base_bottle (
  id              integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  base_id         integer NOT NULL,
  transaction_id  integer NOT NULL,
  date_opened     timestamp(3),
  date_finished   timestamp(3),
  quantity        integer NOT NULL DEFAULT 100,
  CONSTRAINT base_bottle_base_fk
    FOREIGN KEY (base_id) REFERENCES base(base_id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT base_bottle_txn_fk
    FOREIGN KEY (transaction_id) REFERENCES transactions(id)
    ON UPDATE CASCADE ON DELETE RESTRICT
);

-- ======================
-- Ingredients
-- ======================

-- DONE
CREATE TABLE ingredient_type (
  name  text PRIMARY KEY
);

-- DONE
CREATE TABLE ingredient (
  id                      integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name                    text NOT NULL,
  quantity                double precision NOT NULL,
  unit                    text NOT NULL,
  brand                   text,
  ingredient_type_name    text NOT NULL,
  img_path                text NOT NULL,
  present                 boolean NOT NULL,
  CONSTRAINT ingredient_type_fk
    FOREIGN KEY (ingredient_type_name) REFERENCES ingredient_type(name)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT ingredient_unit_fk
    FOREIGN KEY (unit) REFERENCES unit(name)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT ingredient_name_qty_unit_key UNIQUE (name, quantity, unit)
);

-- DONE
CREATE TABLE ingredient_item (
  id              integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  brand           text NOT NULL,
  name            text NOT NULL,
  quantity        double precision NOT NULL,
  unit            text NOT NULL,
  transaction_id  integer NOT NULL,
  date_opened     timestamp(3),
  date_finished   timestamp(3),
  CONSTRAINT ingredient_item_ref_fk
    FOREIGN KEY (name, quantity, unit)
      REFERENCES ingredient(name, quantity, unit)
      ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT ingredient_item_unit_fk
    FOREIGN KEY (unit) REFERENCES unit(name)
      ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT ingredient_item_txn_fk
    FOREIGN KEY (transaction_id) REFERENCES transactions(id)
      ON UPDATE CASCADE ON DELETE RESTRICT
);

-- ======================
-- Tools
-- ======================

-- TOOL
CREATE TABLE tool_type (
  name  text PRIMARY KEY
);

-- DONE
CREATE TABLE tool (
  name             text PRIMARY KEY,
  transaction_id   integer NOT NULL,
  quantity         integer NOT NULL,
  unit             text NOT NULL,
  tool_type_name   text NOT NULL,
  CONSTRAINT tool_type_fk
    FOREIGN KEY (tool_type_name) REFERENCES tool_type(name)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT tool_unit_fk
    FOREIGN KEY (unit) REFERENCES unit(name)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT tool_txn_fk
    FOREIGN KEY (transaction_id) REFERENCES transactions(id)
    ON UPDATE CASCADE ON DELETE RESTRICT
);

-- ======================
-- Drinks & recipes
-- ======================

-- DONE
CREATE TABLE drink (
  name      text PRIMARY KEY,
  img_path  text NOT NULL
);

-- DONE
CREATE TABLE drink_recipe (
  drink_id    integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name        text NOT NULL,        -- references drink.name
  ingredient  text NOT NULL,
  quantity    integer NOT NULL,
  unit        text NOT NULL,
  CONSTRAINT drink_recipe_drink_fk
    FOREIGN KEY (name) REFERENCES drink(name)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT drink_recipe_unit_fk
    FOREIGN KEY (unit) REFERENCES unit(name)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT drink_recipe_name_ingredient_key UNIQUE (name, ingredient)
);

-- DONE
CREATE TABLE drink_variant (
  variant_id        integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  drink_id          integer NOT NULL,   -- references drink_recipe.drink_id
  base_drink        text NOT NULL,      -- references drink.name
  variant_name      text NOT NULL,
  img_overlay_path  text,
  notes             text,
  CONSTRAINT drink_variant_base_drink_fk
    FOREIGN KEY (base_drink) REFERENCES drink(name)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT drink_variant_recipe_fk
    FOREIGN KEY (drink_id) REFERENCES drink_recipe(drink_id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT drink_variant_base_name_key UNIQUE (base_drink, variant_name)
);

CREATE TABLE drink_variant_ingredient (
  variant_id              integer NOT NULL,
  original_ingredient     text NOT NULL,
  replacement_ingredient  text NOT NULL,
  CONSTRAINT drink_variant_ing_variant_fk
    FOREIGN KEY (variant_id) REFERENCES drink_variant(variant_id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT drink_variant_ingredient_pkey PRIMARY KEY (variant_id, original_ingredient)
);
