import db from '../../config/db.js';

export async function up() {
  try {
    await db.query(`
      CREATE TABLE IF NOT EXISTS liquor (
        liquor_id    integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        brand        text NOT NULL,
        name         text NOT NULL,
        ml           integer NOT NULL,
        abv          integer NOT NULL,
        img_path     text NOT NULL,
        liquor_type_name text NOT NULL,
        present      boolean NOT NULL,
        CONSTRAINT liquor_liquor_type_fk
            FOREIGN KEY (liquor_type_name) REFERENCES liquor_type(name)
            ON UPDATE CASCADE ON DELETE RESTRICT,
        CONSTRAINT liquor_brand_name_ml_key UNIQUE (brand, name, ml)
        );
    `);
  } catch (error) {
    console.log(error)
  }
}

export async function down() {
  try {
    await db.query('DROP TABLE IF EXISTS liquor');
  } catch (error) {
    console.log(error)
  }
}

up()