import db from '../../config/db.js';

export async function up() {
  try {
    await db.query(`
      CREATE TABLE IF NOT EXISTS liquor_bottle (
        id              integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        liquor_id       integer NOT NULL,
        transaction_id  integer NOT NULL,
        date_opened     timestamp(3),
        date_finished   timestamp(3),
        quantity        integer NOT NULL DEFAULT 100,
        CONSTRAINT liquor_bottle_liquor_fk
            FOREIGN KEY (liquor_id) REFERENCES liquor(liquor_id)
            ON UPDATE CASCADE ON DELETE RESTRICT,
        CONSTRAINT liquor_bottle_txn_fk
            FOREIGN KEY (transaction_id) REFERENCES transactions(id)
            ON UPDATE CASCADE ON DELETE RESTRICT
        );
    `);
  } catch (error) {
    console.log(error)
  }
}

export async function down() {
  try {
    await db.query('DROP TABLE IF EXISTS liquor_bottle');
  } catch (error) {
    console.log(error)
  }
}

up()