import db from '../../config/db.js';

export async function up() {
  try {
    await db.query(`
      CREATE TABLE IF NOT EXISTS ingredient_item (
        id              integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        brand           text NOT NULL,
        name            text NOT NULL,
        quantity        double precision NOT NULL,
        unit            text NOT NULL,
        transaction_id  integer NOT NULL,
        date_opened     timestamp(3),
        date_finished   timestamp(3),
        CONSTRAINT ingredient_item_ref_fk
            FOREIGN KEY (name, quantity, unit)
            REFERENCES ingredient(name, quantity, unit)
            ON UPDATE CASCADE ON DELETE RESTRICT,
        CONSTRAINT ingredient_item_unit_fk
            FOREIGN KEY (unit) REFERENCES unit(name)
            ON UPDATE CASCADE ON DELETE RESTRICT,
        CONSTRAINT ingredient_item_txn_fk
            FOREIGN KEY (transaction_id) REFERENCES transactions(id)
            ON UPDATE CASCADE ON DELETE RESTRICT
        );
    `);
  } catch (error) {
    console.log(error)
  }
}

export async function down() {
  try {
    await db.query('DROP TABLE IF EXISTS ingredient_item');
  } catch (error) {
    console.log(error)
  }
}

up()