import db from '../../config/db.js';

export async function up() {
  try {
    await db.query(`
      CREATE TABLE IF NOT EXISTS ingredient (
        id                      integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        name                    text NOT NULL,
        quantity                double precision NOT NULL,
        unit                    text NOT NULL,
        brand                   text,
        ingredient_type_name    text NOT NULL,
        img_path                text NOT NULL,
        present                 boolean NOT NULL,
        CONSTRAINT ingredient_type_fk
            FOREIGN KEY (ingredient_type_name) REFERENCES ingredient_type(name)
            ON UPDATE CASCADE ON DELETE RESTRICT,
        CONSTRAINT ingredient_unit_fk
            FOREIGN KEY (unit) REFERENCES unit(name)
            ON UPDATE CASCADE ON DELETE RESTRICT,
        CONSTRAINT ingredient_name_qty_unit_key UNIQUE (name, quantity, unit)
        );
    `);
  } catch (error) {
    console.log(error)
  }
}

export async function down() {
  try {
    await db.query('DROP TABLE IF EXISTS ingredient')
  } catch (error) {
    console.log(error)
  }
}

up()